# Generated by Django 5.1.6 on 2026-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
