# Generated by Django 5.1.6 on 2026-10-02 10:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, help_text='Leave blank to let the system number it.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_kh', models.CharField(blank=True, max_length=150)),
                ('short_name', models.CharField(blank=True, help_text='Used in dropdowns and reports.', max_length=60)),
                ('display_order', models.IntegerField(default=1)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_alt', models.CharField(blank=True, max_length=30)),
                ('telegram', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Cambodia', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('supplier_type', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('IMPORTER', 'Importer'), ('DISTRIBUTOR', 'Distributor'), ('WHOLESALER', 'Wholesaler'), ('SERVICE_CENTRE', 'Service centre'), ('LOCAL_MARKET', 'Local market')], max_length=20)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suppliers/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, help_text='Leave blank to let the system number it.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_kh', models.CharField(blank=True, max_length=150)),
                ('short_name', models.CharField(blank=True, help_text='Used in dropdowns and reports.', max_length=60)),
                ('display_order', models.IntegerField(default=1)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_alt', models.CharField(blank=True, max_length=30)),
                ('telegram', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Cambodia', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('price_tier', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], default='RETAIL', help_text='Loaded automatically at checkout.', max_length=10)),
                ('is_system', models.BooleanField(default=False, editable=False, help_text='The walk-in customer. Exactly one, created by seed.')),
                ('allow_credit', models.BooleanField(default=False, help_text='Off means every sale must be settled at the till.')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='In US dollars.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_terms_days', models.PositiveIntegerField(default=0, help_text='Days. Sets the due date on each credit sale.')),
                ('credit_hold', models.BooleanField(default=False, help_text='Blocks new credit sales without changing the limit. Existing invoices are unaffected.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'code'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('is_system',), name='one_system_customer'), models.CheckConstraint(condition=models.Q(('is_system', False), models.Q(('allow_credit', False), ('is_active', True), ('price_tier', 'RETAIL')), _connector='OR'), name='system_customer_is_retail_cash_active'), models.CheckConstraint(condition=models.Q(models.Q(('allow_credit', True), ('credit_limit__gt', 0)), models.Q(('allow_credit', False), ('credit_hold', False), ('credit_limit', 0), ('payment_terms_days', 0)), _connector='OR'), name='customer_credit_fields_agree')],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_sku', models.CharField(blank=True, help_text="The supplier's own code for this product.", max_length=60)),
                ('pack_size', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Units of the product in the supplier's usual pack.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_preferred', models.BooleanField(default=False, help_text='The supplier to buy from first. One per product.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_links', to='catalogue.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='partners.supplier')),
            ],
            options={
                'ordering': ['product__code', '-is_preferred', 'supplier__code'],
                'constraints': [models.UniqueConstraint(fields=('product', 'supplier'), name='one_link_per_product_supplier'), models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('product',), name='one_preferred_supplier_per_product'), models.CheckConstraint(condition=models.Q(('pack_size__gt', 0)), name='pack_size_is_positive')],
            },
        ),
    ]
