# Generated by Django 5.1.6 on 2026-10-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='pack_unit',
            field=models.ForeignKey(blank=True, help_text="What the supplier's pack is, e.g. Carton. Blank means the product's own unit.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.unit'),
        ),
    ]
