# Generated by Django 5.1.6 on 2026-10-02 05:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_kh', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('display_order', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_kh', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalogue.category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_kh', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='Leave empty if the product has none.', max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_kh', models.CharField(blank=True, max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Must fit one receipt line.', max_length=60)),
                ('model_no', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_price_fixed', models.BooleanField(default=False, help_text='Blocks line discounting at the till.')),
                ('track_stock', models.BooleanField(default=True, help_text='Off for services and labour, which have no quantity.')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shelf_location', models.CharField(blank=True, db_index=True, help_text='Where it sits in the shop, e.g. A3-2. Count sheets sort by it.', max_length=20)),
                ('warranty_months', models.PositiveIntegerField(default=0, help_text='Zero means none. Printed on the receipt.')),
                ('origin_country', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.unit')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['category', 'brand'], name='catalogue_p_categor_687064_idx'), models.Index(fields=['is_active', 'track_stock'], name='catalogue_p_is_acti_2be4ac_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('retail_price__gte', 0), ('wholesale_price__gte', 0)), name='product_prices_not_negative'), models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0), ('reorder_qty__gte', 0)), name='product_reorder_not_negative')],
            },
        ),
    ]
