# Generated by Django 5.1.6 on 2026-10-02 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('doc_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], db_index=True, default='DRAFT', editable=False, max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reason', models.CharField(choices=[('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('SHOP_USE', 'Shop use'), ('WARRANTY_REPLACEMENT', 'Warranty replacement'), ('RETURN_TO_SUPPLIER', 'Return to supplier'), ('SUPPLIER_REPLACEMENT', 'Supplier replacement'), ('OPENING_BALANCE', 'Opening balance')], max_length=25)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.adjustment')),
                ('supplier', models.ForeignKey(blank=True, help_text='For a return to, or a replacement from, a supplier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='partners.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-doc_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('doc_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], db_index=True, default='DRAFT', editable=False, max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.category')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.stockcount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock count',
                'ordering': ['-doc_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('doc_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], db_index=True, default='DRAFT', editable=False, max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('supplier_ref', models.CharField(blank=True, help_text="The supplier's invoice or delivery note number.", max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.stockin')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='partners.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock in',
                'ordering': ['-doc_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='How many. Whether they go in or out is set by the reason.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Typed only for an opening balance; stamped at posting otherwise.', max_digits=12, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.adjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.product')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='adjustment_line_positive')],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('expected_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.product')),
            ],
            options={
                'ordering': ['product__shelf_location', 'product__code'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('document', 'product'), name='one_count_line_per_product')],
            },
        ),
        migrations.CreateModel(
            name='StockInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pack_size', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pack_cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, editable=False, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockin')),
                ('pack_unit', models.ForeignKey(blank=True, help_text="Bought as, e.g. Carton. Blank means the product's own unit.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.product')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('packs__gt', 0), ('pack_size__gt', 0), ('pack_cost__gt', 0)), name='stock_in_line_positive')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Customer payment'), ('RETURN', 'Return'), ('STOCK_IN', 'Stock in'), ('ADJUSTMENT', 'Adjustment'), ('COUNT', 'Stock count'), ('WARRANTY', 'Warranty claim'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=20)),
                ('doc_id', models.PositiveBigIntegerField()),
                ('doc_number', models.CharField(db_index=True, max_length=20)),
                ('line_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, db_index=True, max_length=25)),
                ('is_reversal', models.BooleanField(default=False)),
                ('movement_date', models.DateField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('qty_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_cost_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalogue.product')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product', 'id'], name='inventory_s_product_bca1da_idx'), models.Index(fields=['doc_type', 'doc_id'], name='inventory_s_doc_typ_dd14b6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movement_quantity_not_zero'), models.CheckConstraint(condition=models.Q(('qty_after__gte', 0)), name='movement_never_below_zero')],
            },
        ),
    ]
