# Generated by Django 5.1.6 on 2026-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='doc_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
