# Generated by Django 5.1.6 on 2026-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='doc_type',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Customer payment'), ('RETURN', 'Return'), ('STOCK_IN', 'Stock in'), ('ADJUSTMENT', 'Adjustment'), ('COUNT', 'Stock count'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=20),
        ),
    ]
