# Generated by Django 5.1.6 on 2026-10-06 09:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warranty_number', models.CharField(help_text="From the warranty card or the supplier's sticker.", max_length=40)),
                ('product_code', models.CharField(blank=True, max_length=30)),
                ('product_name', models.CharField(max_length=200)),
                ('warranty_months', models.PositiveSmallIntegerField(default=0, help_text='Zero when the item has none.', validators=[django.core.validators.MaxValueValidator(120)])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('SENT_FOR_REPAIR', 'Sent for repair'), ('READY', 'Ready for collection'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='RECEIVED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
