# Generated by Django 5.1.6 on 2026-10-02 05:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Customer payment'), ('RETURN', 'Return'), ('STOCK_IN', 'Stock in'), ('ADJUSTMENT', 'Adjustment'), ('COUNT', 'Stock count'), ('WARRANTY', 'Warranty claim')], max_length=20, unique=True)),
                ('prefix', models.CharField(max_length=10)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('name_kh', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('vat_tin', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('receipt_header', models.CharField(blank=True, max_length=150)),
                ('receipt_footer', models.TextField(blank=True)),
                ('receipt_paper_width', models.CharField(choices=[('80mm', '80 mm'), ('58mm', '58 mm'), ('A5', 'A5')], default='80mm', max_length=10)),
                ('receipt_language', models.CharField(choices=[('EN', 'English'), ('KH', 'Khmer'), ('BOTH', 'Both')], default='EN', max_length=10)),
                ('receipt_show_riel_total', models.BooleanField(default=True)),
                ('receipt_show_rate_used', models.BooleanField(default=True)),
                ('receipt_show_seller', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company profile',
            },
        ),
        migrations.CreateModel(
            name='PaymentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('payment_type', models.CharField(max_length=150, unique=True)),
                ('payment_info', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_notes/')),
                ('row_order', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['row_order', 'payment_type'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Riel per one US dollar.', max_digits=18, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('effective_date',), name='uniq_rate_per_date'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='rate_is_positive')],
            },
        ),
    ]
