# Generated by Django 5.1.6 on 2026-10-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcounter',
            name='doc_type',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Customer payment'), ('RETURN', 'Return'), ('STOCK_IN', 'Stock in'), ('ADJUSTMENT', 'Adjustment'), ('COUNT', 'Stock count'), ('WARRANTY', 'Warranty claim'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=20, unique=True),
        ),
    ]
