# Generated by Django 5.1.6 on 2026-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcounter',
            name='number_date',
            field=models.DateField(blank=True, editable=False, help_text='The day next_number counts for. Daily types only.', null=True),
        ),
    ]
