# Generated by Django 5.1.6 on 2026-10-06 09:10

from django.db import migrations, models


def drop_warranty_counter(apps, schema_editor):
    # Claims are known by the number on the warranty card; nothing used it.
    apps.get_model("company", "DocumentCounter").objects.filter(doc_type="WARRANTY").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_documentcounter_number_date'),
    ]

    operations = [
        migrations.RunPython(drop_warranty_counter, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documentcounter',
            name='doc_type',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Customer payment'), ('RETURN', 'Return'), ('STOCK_IN', 'Stock in'), ('ADJUSTMENT', 'Adjustment'), ('COUNT', 'Stock count'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=20, unique=True),
        ),
    ]
