# Generated by Django 5.1.6 on 2026-10-05 03:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('tender', models.CharField(choices=[('CASH', 'Cash'), ('KHQR', 'KHQR'), ('BANK', 'Bank transfer')], max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('KHR', 'Riel')], default='USD', max_length=3)),
                ('amount_tendered', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='In US dollars.', max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('VOID', 'Void')], db_index=True, default='POSTED', editable=False, max_length=10)),
                ('void_reason', models.TextField(blank=True, editable=False)),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('COMPLETED', 'Completed'), ('VOID', 'Void')], db_index=True, default='HELD', editable=False, max_length=10)),
                ('walk_in_name', models.CharField(blank=True, max_length=100)),
                ('walk_in_phone', models.CharField(blank=True, max_length=30)),
                ('price_tier', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], editable=False, max_length=10)),
                ('hold_label', models.CharField(blank=True, max_length=60)),
                ('sale_date', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('paid_now', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('on_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('change_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('change_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('change_khr', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=14)),
                ('rounding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('due_date', models.DateField(blank=True, editable=False, null=True)),
                ('void_reason', models.TextField(blank=True, editable=False)),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.customer')),
                ('seller', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CASH', 'Cash'), ('KHQR', 'KHQR'), ('CREDIT', 'Credit')], max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('KHR', 'Riel')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, help_text='In its own currency.', max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='sales.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('price_tier', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], editable=False, max_length=10)),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('INVOICED', 'Invoiced')], db_index=True, default='DRAFT', editable=False, max_length=10)),
                ('terms', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='partners.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quote_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.quotation'),
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENT', '%'), ('AMOUNT', '$ per unit')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent (0–15), or dollars off each unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('qty_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotation')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENT', '%'), ('AMOUNT', '$ per unit')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent (0–15), or dollars off each unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.product')),
                ('quote_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='sales.quotationline')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField()),
                ('refund_method', models.CharField(blank=True, choices=[('CASH', 'Cash refund'), ('KHQR', 'KHQR refund')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], db_index=True, default='DRAFT', editable=False, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='partners.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.invoice')),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fit_to_sell', models.BooleanField(default=True, help_text='Off for a faulty item: it does not go back into stock.')),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned', to='sales.invoiceline')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.customerpayment')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='allocation_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'HELD'), ('number__isnull', False), _connector='OR'), name='completed_invoice_has_number'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_invoiced__lte', models.F('quantity'))), name='quote_line_not_over_invoiced'),
        ),
    ]
