# Generated by Django 5.1.6 on 2026-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
